site_name: Metro's Documentation
theme: 
  name: 'material'
  logo: 'images/metro_icon.png'
  features:
    - tabs
    - instant
  palette:
    scheme: preference
    primary: 'Blue Grey'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  
repo_name: 'metro'
repo_url: 'https://github.com/dartmern/metro_docs'

name: metro_docs
on:
  push:
    branches: 
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force

copyright: 'Copyright &copy; 2022 - Present, dartmern. All Rights Reserved.'